name: sheep
description: A new Flutter project.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  iconly: ^1.0.1
  flutter_iconly: ^1.0.2
  flutter_floating_bottom_bar: ^1.2.0
  cr_calendar: ^1.2.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  page_transition: ^2.0.4
  flutter_launcher_icons: "^0.13.1"
  

flutter_launcher_icons:
  android: true
  ios: true
  widowns: true
  image_path: "assets/iconApp.png"


flutter:
  uses-material-design: true
  assets: 
  - assets/logo.png
  - assets/sheep.png
  - assets/sheep2.png
  - assets/sheepy.png
  - assets/cat.png
  - assets/3.png
  - assets/4.png
  - assets/form.png
  - assets/ovelha1.png
  - assets/ovelha2.png
  - assets/ovelha3.png
  - assets/ovelha4.png
  
  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
