name: sheep
description: A new Flutter project.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  page_transition: ^2.0.4
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  widowns: true
  image_path: "assets/iconApp.png"


flutter:
  uses-material-design: true
  assets: 
  - assets/logo.png
  - assets/sheep.png
  - assets/sheep2.png
  - assets/add.png
  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
